// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "MeshViewUI.h"

void MeshViewUI::cb_zoomSlider_i(Fl_Value_Slider* o, void*) {
  meshView->setControlSize(o->value());
meshView->redraw();
}
void MeshViewUI::cb_zoomSlider(Fl_Value_Slider* o, void* v) {
  ((MeshViewUI*)(o->parent()->parent()->user_data()))->cb_zoomSlider_i(o,v);
}

Fl_Menu_Item MeshViewUI::menu_[] = {
 {"\346\226\207\344\273\266", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"\351\200\200\345\207\272(Quit)", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};

void MeshViewUI::cb_Edit_i(Fl_Round_Button*, void*) {
  meshView->setDragType(MeshView::DRAG_EDIT);
}
void MeshViewUI::cb_Edit(Fl_Round_Button* o, void* v) {
  ((MeshViewUI*)(o->parent()->parent()->user_data()))->cb_Edit_i(o,v);
}

void MeshViewUI::cb_View_i(Fl_Round_Button*, void*) {
  meshView->setDragType(MeshView::DRAG_VIEW);
}
void MeshViewUI::cb_View(Fl_Round_Button* o, void* v) {
  ((MeshViewUI*)(o->parent()->parent()->user_data()))->cb_View_i(o,v);
}

MeshViewUI::MeshViewUI() {
  { mContainer = new Fl_Double_Window(917, 688);
    mContainer->user_data((void*)(this));
    { mFl_Group = new Fl_Group(15, 15, 895, 665);
      { MainView = new Fl_Group(15, 40, 890, 640);
        { meshView = new MeshView(15, 84, 890, 550);
          meshView->box(FL_NO_BOX);
          meshView->color((Fl_Color)68);
          meshView->selection_color(FL_BACKGROUND_COLOR);
          meshView->labeltype(FL_NORMAL_LABEL);
          meshView->labelfont(0);
          meshView->labelsize(14);
          meshView->labelcolor(FL_FOREGROUND_COLOR);
          meshView->align(Fl_Align(FL_ALIGN_CENTER));
          meshView->when(FL_WHEN_RELEASE);
        } // MeshView* meshView
        MainView->end();
      } // Fl_Group* MainView
      { zoomSlider = new Fl_Value_Slider(15, 645, 895, 20, "Zoom");
        zoomSlider->type(1);
        zoomSlider->minimum(1);
        zoomSlider->maximum(3);
        zoomSlider->value(1);
        zoomSlider->textsize(14);
        zoomSlider->callback((Fl_Callback*)cb_zoomSlider);
      } // Fl_Value_Slider* zoomSlider
      mFl_Group->end();
    } // Fl_Group* mFl_Group
    { Fl_Menu_Bar* o = new Fl_Menu_Bar(0, 0, 916, 20);
      o->menu(menu_);
    } // Fl_Menu_Bar* o
    { Fl_Group* o = new Fl_Group(10, 45, 150, 35, "Drag");
      o->box(FL_FLAT_BOX);
      { Fl_Round_Button* o = new Fl_Round_Button(100, 50, 60, 30, "Edit");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->callback((Fl_Callback*)cb_Edit);
      } // Fl_Round_Button* o
      { Fl_Round_Button* o = new Fl_Round_Button(25, 50, 75, 30, "View");
        o->type(102);
        o->down_box(FL_ROUND_DOWN_BOX);
        o->value(1);
        o->callback((Fl_Callback*)cb_View);
      } // Fl_Round_Button* o
      o->end();
    } // Fl_Group* o
    mContainer->end();
  } // Fl_Double_Window* mContainer
}

/**
   show the window
*/
void MeshViewUI::show() {
  mContainer->show();
}
