// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "MeshViewUI.h"

void MeshViewUI::cb_zoomSlider_i(Fl_Value_Slider* o, void*) {
	meshView->setControlSize(o->value());
	meshView->redraw();
}
void MeshViewUI::cb_zoomSlider(Fl_Value_Slider* o, void* v) {
  ((MeshViewUI*)(o->parent()->parent()->user_data()))->cb_zoomSlider_i(o,v);
}

MeshViewUI::MeshViewUI() {
  { mContainer = new Fl_Double_Window(924, 684);
    mContainer->user_data((void*)(this));
    { mFl_Group = new Fl_Group(15, 15, 895, 665);
      { VChange = new Fl_Group(15, 20, 305, 650);
        { vrot = new Fl_Roller(15, 70, 25, 600);
        } // Fl_Roller* vrot
        { ypan = new Fl_Slider(45, 70, 20, 600);
        } // Fl_Slider* ypan
        VChange->end();
      } // Fl_Group* VChange
      { HChange = new Fl_Group(40, 15, 845, 360);
        { xpan = new Fl_Slider(115, 50, 770, 25);
          xpan->type(1);
          xpan->window()->hotspot(xpan);
        } // Fl_Slider* xpan
        { hrot = new Fl_Roller(115, 15, 770, 25);
          hrot->type(1);
        } // Fl_Roller* hrot
        HChange->end();
      } // Fl_Group* HChange
      { MainView = new Fl_Group(40, 40, 865, 640);
        { meshView = new MeshView(90, 92, 795, 546);
          meshView->box(FL_NO_BOX);
          meshView->color((Fl_Color)68);
          meshView->selection_color(FL_BACKGROUND_COLOR);
          meshView->labeltype(FL_NORMAL_LABEL);
          meshView->labelfont(0);
          meshView->labelsize(14);
          meshView->labelcolor(FL_FOREGROUND_COLOR);
          meshView->align(Fl_Align(FL_ALIGN_CENTER));
          meshView->when(FL_WHEN_RELEASE);
        } // MeshView* meshView
        MainView->end();
      } // Fl_Group* MainView
      { zoomSlider = new Fl_Value_Slider(60, 645, 850, 25, "Zoom");
        zoomSlider->type(1);
        zoomSlider->minimum(1);
        zoomSlider->maximum(3);
        zoomSlider->value(1);
        zoomSlider->textsize(14);
        zoomSlider->callback((Fl_Callback*)cb_zoomSlider);
      } // Fl_Value_Slider* zoomSlider
      mFl_Group->end();
    } // Fl_Group* mFl_Group
    mContainer->end();
  } // Fl_Double_Window* mContainer
}

/**
   show the window
*/
void MeshViewUI::show() {
  mContainer->show();
}
